Fix NoClassDefFoundError due to CursorAnchorInfo in K
Check API level before touching CursorAnchorInfo that is only
available in L and later.

BUG: 17891202
Change-Id: I6e8d2e3f071bd78bed8c1d24ba2b97207dea3044